---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
    - name: Install httpd package
      command: yum install -y httpd 
    - name: copy index.html
      shell: echo "hello" > /var/www/html/index.html
    - name: start the httpd service
      raw: systemctl start httpd
    - name: execute the script
      script: ./script.sh
