---
- hosts: '{{host}}' 
  remote_user: test
  become: yes
  vars:
     pkg: httpd
  vars_files:
    - abc.yml
  vars_prompt:
     - name: pkg2
       prompt: Enter package name
       private: no
  tasks:
    - name: Install httpd package
      yum: name={{pkg}} state=installed
    - name: install {{pkg1}}
      yum: name={{pkg1}} state=installed
    - name: install {{pkg2}}
      yum: name={{pkg2}} state=installed
    - name: copy index.html
      copy: src=index.html dest=/var/www/html
    - name: start the httpd service
      service: name={{pkg}} state=started
